name: lankago
description: "Your ultimate travel companion for exploring Sri Lanka. Discover hidden gems, plan your routes, and navigate the beautiful island with ease using LankaGo - the essential app for tourists and locals alike."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.4
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
    - assets/images/backgrounds/
    - assets/images/icons/
    - .env
